package top.kenetgit.springbootdemo.pojo;

import javax.persistence.*;

@Table(name = "`tb_goods`")
public class TbGoods {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_goods.id
     *
     * @mbggenerated Tue Feb 12 00:51:14 CST 2019
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_goods.title
     *
     * @mbggenerated Tue Feb 12 00:51:14 CST 2019
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_goods.price
     *
     * @mbggenerated Tue Feb 12 00:51:14 CST 2019
     */
    private String price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_goods.image
     *
     * @mbggenerated Tue Feb 12 00:51:14 CST 2019
     */
    private String image;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_goods.brand
     *
     * @mbggenerated Tue Feb 12 00:51:14 CST 2019
     */
    private String brand;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_goods.id
     *
     * @return the value of tb_goods.id
     *
     * @mbggenerated Tue Feb 12 00:51:14 CST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_goods.id
     *
     * @param id the value for tb_goods.id
     *
     * @mbggenerated Tue Feb 12 00:51:14 CST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_goods.title
     *
     * @return the value of tb_goods.title
     *
     * @mbggenerated Tue Feb 12 00:51:14 CST 2019
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_goods.title
     *
     * @param title the value for tb_goods.title
     *
     * @mbggenerated Tue Feb 12 00:51:14 CST 2019
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_goods.price
     *
     * @return the value of tb_goods.price
     *
     * @mbggenerated Tue Feb 12 00:51:14 CST 2019
     */
    public String getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_goods.price
     *
     * @param price the value for tb_goods.price
     *
     * @mbggenerated Tue Feb 12 00:51:14 CST 2019
     */
    public void setPrice(String price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_goods.image
     *
     * @return the value of tb_goods.image
     *
     * @mbggenerated Tue Feb 12 00:51:14 CST 2019
     */
    public String getImage() {
        return image;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_goods.image
     *
     * @param image the value for tb_goods.image
     *
     * @mbggenerated Tue Feb 12 00:51:14 CST 2019
     */
    public void setImage(String image) {
        this.image = image;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_goods.brand
     *
     * @return the value of tb_goods.brand
     *
     * @mbggenerated Tue Feb 12 00:51:14 CST 2019
     */
    public String getBrand() {
        return brand;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_goods.brand
     *
     * @param brand the value for tb_goods.brand
     *
     * @mbggenerated Tue Feb 12 00:51:14 CST 2019
     */
    public void setBrand(String brand) {
        this.brand = brand;
    }
}